import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from './navbar'
import Header from './header'
import Services from './services'
import { Router } from 'next/router'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='max-w-[1440px] mx-auto'>
        <Navbar />
        <Header />
        <Services />
      </main>
    </>
  )
}
